name: CI

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'README*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -Pnative install
      - name: Build with Maven
        run: mvn -Pnative-image install -f integration-tests/